name: delete formula
on:
  workflow_dispatch:
    inputs:
      formula:
        description: Formula name to delete.
        required: true
        type: string
      dry-run:
        description: Show the deletion without committing.
        required: false
        type: boolean
        default: false
permissions:
  contents: read
jobs:
  delete:
    permissions:
      contents: write
    uses: releaseway/homebrew-actions/.github/workflows/tap-delete.yml@4bbfa6aafc92a6cb8e823a51d54a6573237e0a76 # v0.2.0
    with:
      formula: ${{ inputs.formula }}
      dry-run: ${{ inputs.dry-run }}
