name: test
on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  tap-check:
    uses: releaseway/homebrew-actions/.github/workflows/tap-check.yml@5e6570fec2e5d16ad61868877da3a175fac99479 # v0.3.5
