name: test
on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  tap-check:
    uses: releaseway/homebrew-actions/.github/workflows/tap-check.yml@4bbfa6aafc92a6cb8e823a51d54a6573237e0a76 # v0.2.0
