name: test
on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  tap-check:
    uses: releaseway/homebrew-actions/.github/workflows/tap-check.yml@b947bedda8122de8b5c13b41416c3651a7841ae1 # v0.3.4
